Repository DIT112-V21/group-17, pull requests merged in 2021-04, with the labels that each got.

#18 Updating the Read me file
  README.md
Labels: documentation

#19 Update README.md
  README.md
Labels: documentation

#21 Add basic Android application set-up
  .idea/.gitignore
  .idea/gradle.xml
  .idea/group-17.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Android/.gitignore
  Android/.idea/.gitignore
  Android/.idea/compiler.xml
  Android/.idea/gradle.xml
  Android/.idea/jarRepositories.xml
  Android/.idea/misc.xml
  Android/.idea/vcs.xml
  Android/app/.gitignore
  Android/app/build.gradle
  Android/app/proguard-rules.pro
  Android/app/src/androidTest/java/com/example/android/ExampleInstrumentedTest.java
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/android/MainActivity.java
  Android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Android/app/src/main/res/drawable/ic_launcher_background.xml
  Android/app/src/main/res/layout/activity_main.xml
  Android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Android/app/src/main/res/values-night/themes.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/themes.xml
  Android/app/src/test/java/com/example/android/ExampleUnitTest.java
  Android/build.gradle
  Android/gradle.properties
  Android/gradle/wrapper/gradle-wrapper.jar
  Android/gradle/wrapper/gradle-wrapper.properties
  Android/gradlew
  Android/gradlew.bat
  Android/settings.gradle
Labels: sprint1

#20 Obstacle avoidance
  arduino/smartcar/smartcar.ino
Labels: sprint1

#23 Update rotation obstacle avoidance
  arduino/smartcar/smartcar.ino
Labels: ArduinoCode, Tested, Works, sprint1

#45 Mqtt connectivity
  .github/workflows/arduino-build.yml
  android/.idea/.name
  android/.idea/jarRepositories.xml
  android/.idea/markdown-navigator-enh.xml
  android/.idea/markdown-navigator.xml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/android/MainActivity.java
  android/app/src/main/java/com/example/android/ManualActivity.java
  android/app/src/main/java/com/example/android/MqttClient.java
  android/app/src/main/res/layout/activity_manual.xml
  android/build.gradle
  arduino/smartcar/smartcar.ino
Labels: Sprint2
